theme: jekyll-theme-cayman
title: Group 00
description: A Great Transition project
cover-image: https://pbs.twimg.com/profile_banners/903380300620849153/1504220447/1500x500
menu: [
  {'name': 'Home', 'pagename': 'index'}, 
  {'name': 'Resources', 'pagename': 'resources'},
  {'name': 'About us', 'pagename': 'about'},
]
