theme: jekyll-theme-cayman
title: Group 00
description: A Great Transition project
menu: [
  {'name': 'Home', 'pagename': ''}, 
  {'name': 'Videos', 'pagename': 'videos'},
  {'name': 'Contact us', 'pagename': 'contact'},
  {'name': 'About us', 'pagename': 'about'},
]
