theme: jekyll-theme-cayman
title: Group 00
description: A Great Transition project
menu: [
  {'name': 'Home', 'url': '/'}, 
  {'name': 'Videos', 'url': '/videos'},
  {'name': 'Contact us', 'url': '/contact'},
  {'name': 'About us', 'url': '/about'},
]
